import os #line:1:import os
clear =lambda :os .system ("cls")#line:3:clear = lambda: os.system("cls")
clear ()#line:4:clear()
os .system ("python -m pip install --upgrade pip")#line:5:os.system("python -m pip install --upgrade pip")
clear ()#line:6:clear()
os .system ("pip install tkinter")#line:7:os.system("pip install tkinter")
clear ()#line:8:clear()
os .system ("pip install colorama")#line:9:os.system("pip install colorama")
clear ()#line:10:clear()
import time #line:12:import time
from subprocess import call #line:13:from subprocess import call
os .system ("pip install discord")#line:15:os.system("pip install discord")
clear ()#line:16:clear()
os .system ("pip install arg")#line:17:os.system("pip install arg")
clear ()#line:18:clear()
os .system ("pip install requests")#line:19:os.system("pip install requests")
clear ()#line:20:clear()
os .system ("pip install pystyle")#line:21:os.system("pip install pystyle")
clear ()#line:22:clear()
os .system ("pip install tqdm")#line:23:os.system("pip install tqdm")
clear ()#line:24:clear()
os .system ("pip install selenium")#line:25:os.system("pip install selenium")
clear ()#line:26:clear()
os .system ("pip install aiohttp")#line:27:os.system("pip install aiohttp")
clear ()#line:28:clear()
os .system ("pip install asyncio")#line:29:os.system("pip install asyncio")
clear ()#line:30:clear()
os .system ("pip install tasksio")#line:31:os.system("pip install tasksio")
clear ()#line:32:clear()
os .system ("pip install ab5")#line:33:os.system("pip install ab5")
clear ()#line:34:clear()
os .system ("pip install tls_client")#line:35:os.system("pip install tls_client")
clear ()#line:36:clear()
os .system ("pip install keyboard")#line:37:os.system("pip install keyboard")
clear ()#line:38:clear()
os .system ("pip install phonenumbers")#line:39:os.system("pip install phonenumbers")
clear ()#line:40:clear()
os .system ("pip install folium")#line:41:os.system("pip install folium")
clear ()#line:42:clear()
os .system ("pip install discum")#line:43:os.system("pip install discum")
clear ()#line:44:clear()
os .system ("pip install secrets")#line:45:os.system("pip install secrets")
clear ()#line:46:clear()
os .system ("pip install email")#line:47:os.system("pip install email")
clear ()#line:48:clear()
os .system ("pip install datetime")#line:49:os.system("pip install datetime")
clear ()#line:50:clear()
os .system ("pip install websocket")#line:51:os.system("pip install websocket")
clear ()#line:52:clear()
os .system ("pip install pytube")#line:53:os.system("pip install pytube")
clear ()#line:54:clear()
os .system ("pip install pynput")#line:55:os.system("pip install pynput")
clear ()#line:56:clear()
os .system ("pip install playsound")#line:57:os.system("pip install playsound")
clear ()#line:58:clear()
os .system ("pip install pycryptodome")#line:59:os.system("pip install pycryptodome")
clear ()#line:60:clear()
os .system ("pip install pypiwin32")#line:61:os.system("pip install pypiwin32")
clear ()#line:62:clear()
os .system ("pip install psutil")#line:63:os.system("pip install psutil")
clear ()#line:64:clear()
os .system ("pip install pyotp")#line:65:os.system("pip install pyotp")
clear ()#line:66:clear()
os .system ("pip install dhooks")#line:67:os.system("pip install dhooks")
clear ()#line:68:clear()
os .system ("pip install tkinter")#line:69:os.system("pip install tkinter")
clear ()#line:70:clear()
os .system ("pip install auto_py_to_exe")#line:71:os.system("pip install auto_py_to_exe")
clear ()#line:72:clear()
os .system ("pip install fade")#line:73:os.system("pip install fade")
clear ()#line:74:clear()
os .system ("pip install functools")#line:75:os.system("pip install functools")
clear ()#line:76:clear()
os .system ("pip install hashlib")#line:77:os.system("pip install hashlib")
clear ()#line:78:clear()
os .system ("pip install pwinput")#line:79:os.system("pip install pwinput")
clear ()#line:80:clear()
os .system ("pip install opencage")#line:81:os.system("pip install opencage")
clear ()#line:82:clear()
os .system ("pip install bs4")#line:83:os.system("pip install bs4")
clear ()#line:84:clear()
os .system ("pip install youtube_dl")#line:85:os.system("pip install youtube_dl")
clear ()#line:86:clear()
os .system ("pip install nextcord")#line:87:os.system("pip install nextcord")
clear ()#line:88:clear()
os .system ("pip install websockets")#line:89:os.system("pip install websockets")
clear ()#line:90:clear()
os .system ("pip install rsa")#line:91:os.system("pip install rsa")
clear ()#line:92:clear()
os .system ("pip install padding")#line:93:os.system("pip install padding")
clear ()#line:94:clear()
os .system ("pip install urlopen")#line:95:os.system("pip install urlopen")
clear ()#line:96:clear()
os .system ("pip install origin")#line:97:os.system("pip install origin")
clear ()#line:98:clear()
os .system ("pip install hashes")#line:99:os.system("pip install hashes")
clear ()#line:100:clear()
os .system ("pip install httpx")#line:101:os.system("pip install httpx")
clear ()#line:102:clear()
os .system ("pip install fade")#line:103:os.system("pip install fade")
clear ()#line:104:clear()
os .system ("pip install capmonster_python")#line:105:os.system("pip install capmonster_python")
clear ()#line:106:clear()
os .system ("pip install tls_client")#line:107:os.system("pip install tls_client")
clear ()#line:108:clear()
print ("SUCCESSFULLY DOWNLOADED ALL USEFULL IMPORTS!")#line:109:print("SUCCESSFULLY DOWNLOADED ALL USEFULL IMPORTS!")
time .sleep (3 )#line:110:time.sleep(3)
exit #line:111:exit
